<a href="https://colab.research.google.com/github/Somenpradhan/EDA-Notes/blob/main/NumPy_Mastyer_E_Book.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <span style="color:blue">1. Introduction to NumPy</span>
## <span style="color:green">1.1 Overview of NumPy</span>
- Importance and advantages
- Installation and setup

## <span style="color:green">1.2 Understanding Arrays</span>
- The difference between lists and arrays
- Introduction to NumPy arrays

# <span style="color:blue">2. NumPy Arrays</span>
## <span style="color:green">2.1 Creating NumPy Arrays</span>
- Creating arrays from lists and tuples
- `np.array()` and data types
- Creating arrays with functions: `np.zeros()`, `np.ones()`, `np.full()`, `np.empty()`, `np.arange()`, `np.linspace()`

## <span style="color:green">2.2 Array Attributes</span>
- Array dimensions: `ndim`, `shape`, `size`, `dtype`, `itemsize`
- Reshaping arrays: `reshape()` and `ravel()`

# <span style="color:blue">3. Array Indexing and Slicing</span>
## <span style="color:green">3.1 Indexing in NumPy</span>
- 1D, 2D, and multi-dimensional arrays
- Accessing individual elements

## <span style="color:green">3.2 Slicing NumPy Arrays</span>
- Slicing arrays using colon `:`
- Using steps and reverse slicing

## <span style="color:green">3.3 Advanced Indexing</span>
- Boolean indexing
- Fancy indexing with arrays of indices

# <span style="color:blue">4. Array Operations</span>
## <span style="color:green">4.1 Basic Arithmetic Operations</span>
- Element-wise addition, subtraction, multiplication, and division
- Broadcasting concept in NumPy

## <span style="color:green">4.2 Mathematical Functions</span>
- Using built-in NumPy functions: `np.add()`, `np.subtract()`, `np.multiply()`, `np.divide()`
- Aggregation functions: `np.sum()`, `np.prod()`, `np.mean()`, `np.std()`, `np.var()`

## <span style="color:green">4.3 Linear Algebra Operations</span>
- Matrix multiplication: `np.dot()`
- Determinants, eigenvalues, and inverse: `np.linalg.det()`, `np.linalg.inv()`
- Solving linear equations: `np.linalg.solve()`

# <span style="color:blue">5. NumPy Array Manipulation</span>
## <span style="color:green">5.1 Joining and Splitting Arrays</span>
- Concatenating arrays: `np.concatenate()`, `np.vstack()`, `np.hstack()`
- Splitting arrays: `np.split()`, `np.vsplit()`, `np.hsplit()`

## <span style="color:green">5.2 Transposing and Swapping Axes</span>
- Transposing arrays: `np.transpose()`
- Changing array axes with `np.swapaxes()`

# <span style="color:blue">6. Broadcasting in NumPy</span>
## <span style="color:green">6.1 Introduction to Broadcasting</span>
- What is broadcasting?
- Rules of broadcasting

## <span style="color:green">6.2 Broadcasting Examples</span>
- Practical examples of broadcasting in array operations

# <span style="color:blue">7. Working with Random Numbers</span>
## <span style="color:green">7.1 Random Number Generation</span>
- Generating random numbers: `np.random.rand()`, `np.random.randint()`
- Random sampling and shuffling: `np.random.shuffle()`

## <span style="color:green">7.2 Statistical Distributions</span>
- Working with normal, uniform, and binomial distributions

# <span style="color:blue">8. NumPy for Data Analysis</span>
## <span style="color:green">8.1 Statistical Functions</span>
- Calculating minimum, maximum, percentiles: `np.min()`, `np.max()`, `np.percentile()`
- Cumulative sum and product: `np.cumsum()`, `np.cumprod()`

## <span style="color:green">8.2 Sorting and Searching in Arrays</span>
- Sorting arrays: `np.sort()`
- Searching elements in arrays: `np.where()`, `np.searchsorted()`

# <span style="color:blue">9. NumPy and Memory Efficiency</span>
## <span style="color:green">9.1 Memory Layout</span>
- Understanding array memory layout: C-order vs F-order

## <span style="color:green">9.2 Memory Efficient Operations</span>
- In-place operations
- Copying vs viewing arrays: `copy()` vs `view()`

# <span style="color:blue">10. NumPy for Advanced Users</span>
## <span style="color:green">10.1 Structured Arrays</span>
- Creating and manipulating structured arrays
- Accessing structured array fields

## <span style="color:green">10.2 Masked Arrays</span>
- Working with missing data using masked arrays

# <span style="color:blue">11. File Input/Output with NumPy</span>
## <span style="color:green">11.1 Saving and Loading Arrays</span>
- Saving arrays to text and binary files: `np.savetxt()`, `np.save()`
- Loading arrays from files: `np.loadtxt()`, `np.load()`

## <span style="color:green">11.2 Working with .npy and .npz files</span>
- Saving multiple arrays in one file with `np.savez()`

# <span style="color:blue">12. Best Practices and Optimization</span>
## <span style="color:green">12.1 Best Practices in NumPy</span>
- Choosing data types for performance
- Avoiding unnecessary array copying

## <span style="color:green">12.2 Performance Optimization</span>
- Vectorization and avoiding loops
- Using `numexpr` and `cython` for performance improvements


****
# 1. Introduction to NumPy

## 1.1 Overview of NumPy

### Importance and Advantages of NumPy

NumPy (Numerical Python) is one of the core libraries for scientific computing in Python. It provides powerful data structures, primarily arrays, that allow for efficient storage and manipulation of large datasets. Some of the key advantages include:

- **Efficient memory usage**: NumPy arrays are stored more compactly than Python lists, making it faster and more memory efficient, especially when working with large datasets.
- **Mathematical operations**: NumPy provides built-in support for many mathematical operations such as element-wise addition, subtraction, multiplication, and linear algebra functions, which are optimized for performance.
- **Support for multidimensional arrays**: Unlike Python lists, NumPy arrays can handle n-dimensional data (1D, 2D, 3D, and higher dimensions).
- **Broadcasting**: NumPy can perform operations between arrays of different shapes (without copying data), which is not directly possible in regular Python lists.
- **Integration with other libraries**: Libraries like Pandas, SciPy, TensorFlow, and many others are built on top of NumPy, making it a foundational tool for data science and machine learning.

### Installation and Setup

You can install NumPy using `pip` (the Python package installer) or `conda` (if you're using the Anaconda distribution).


**1. using pip**

In [ ]:
pip install numpy

**2. using conda**

In [ ]:
conda install numpy

- Once installed, you can import it into your Python script or Jupyter Notebook:

In [ ]:
import numpy as np # Here, np is a common alias for NumPy.

## 1.2 Understanding Arrays

### The Difference Between Lists and Arrays

#### Python Lists:
- Python lists are versatile and can store elements of different data types (e.g., integers, floats, strings, etc.).
- They are slower when performing numerical operations, as they are general-purpose containers.

#### NumPy Arrays:
- NumPy arrays are homogeneous (i.e., they store elements of the same data type, usually numbers).
- They are optimized for numerical computations, providing faster operations compared to Python lists, especially when handling large datasets.

### Example Comparison
Here’s an example to compare a Python list and a NumPy array:


In [ ]:
# Using a Python list
py_list = [1, 2, 3, 4]
print(f"Python List: {py_list}")

# Using a NumPy array
import numpy as np
np_array = np.array([1, 2, 3, 4])
print(f"NumPy Array: {np_array}")

Python List: [1, 2, 3, 4]
NumPy Array: [1 2 3 4]


### Differences:

- Python lists can store elements of different types (e.g., `[1, "two", 3.0]`), while NumPy arrays are homogeneous (e.g., all elements are integers or floats).
- NumPy arrays provide more efficient storage and faster operations for large-scale numerical computations.


## Introduction to NumPy Arrays

A NumPy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers. The number of dimensions (`ndim`) is the rank of the array, and the shape of the array is a tuple of integers giving the size of the array along each dimension.

### Creating a NumPy Array

You can create a NumPy array from a Python list or tuple using the `np.array()` function.

In [ ]:
import numpy as np

# Creating a 1D array (from a Python list)
arr1 = np.array([1, 2, 3, 4])
print("1D NumPy Array:", arr1)

# Creating a 2D array (from a nested Python list)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D NumPy Array:\n", arr2)

1D NumPy Array: [1 2 3 4]
2D NumPy Array:
 [[1 2 3]
 [4 5 6]]


****
# 2. NumPy Arrays

## 2.1 Creating NumPy Arrays

NumPy arrays are at the core of the library. They allow efficient storage and manipulation of data, especially for numerical computations. Let's explore the different ways to create NumPy arrays and the various functions used to do so.

### Creating Arrays from Lists and Tuples

You can easily convert a Python list or tuple into a NumPy array using the `np.array()` function. NumPy arrays are homogeneous, meaning all the elements are of the same data type.


In [ ]:
import numpy as np

# Creating a 1D NumPy array from a Python list
arr_from_list = np.array([1, 2, 3, 4])
print("1D Array from list:", arr_from_list)

# Creating a 1D NumPy array from a Python tuple
arr_from_tuple = np.array((5, 6, 7, 8))
print("1D Array from tuple:", arr_from_tuple)

# Creating a 2D NumPy array from a nested list
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array from nested list:\n", arr_2d)

1D Array from list: [1 2 3 4]
1D Array from tuple: [5 6 7 8]
2D Array from nested list:
 [[1 2 3]
 [4 5 6]]


### `np.array()` and Data Types

By default, NumPy infers the data type of the elements in an array. You can explicitly specify the data type using the `dtype` argument when creating an array.

In [ ]:
# Creating a NumPy array with a specific data type
float_array = np.array([1, 2, 3, 4], dtype=float)
print("Array with float data type:", float_array)

# Creating an integer array
int_array = np.array([1.5, 2.7, 3.9], dtype=int)
print("Array with integer data type:", int_array)


Array with float data type: [1. 2. 3. 4.]
Array with integer data type: [1 2 3]


### Creating Arrays with Functions

NumPy provides several functions to create arrays without manually specifying the elements.

1. `np.zeros(shape)`: Creates an array filled with zeros.

In [ ]:
zeros_array = np.zeros((2, 3))
print("Array of zeros:\n", zeros_array)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


2. `np.ones(shape)`: Creates an array filled with ones.

In [ ]:
ones_array = np.ones((3, 4))
print("Array of ones:\n", ones_array)

Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


3. `np.full(shape, value)`: Creates an array filled with a specified value.

In [ ]:
full_array = np.full((2, 2), 7)
print("Array filled with 7:\n", full_array)

Array filled with 7:
 [[7 7]
 [7 7]]


4. `np.empty(shape)`:Creates an array without initializing the values (useful for performance when the values will be set later).

In [ ]:
empty_array = np.empty((3, 3))
print("Empty array:\n", empty_array)

Empty array:
 [[0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 6.68e-321]
 [0.00e+000 0.00e+000 0.00e+000]]


5. `np.arange(start, stop, step)`: Creates an array with evenly spaced values within a given range.

In [ ]:
range_array = np.arange(0, 10, 2)
print("Array with a range of values:", range_array)

Array with a range of values: [0 2 4 6 8]


6. `np.linspace(start, stop, num)`: Creates an array with `num` evenly spaced numbers between `start` and `stop`.

In [ ]:
linspace_array = np.linspace(0, 1, 5)
print("Array with 5 evenly spaced numbers:", linspace_array)


Array with 5 evenly spaced numbers: [0.   0.25 0.5  0.75 1.  ]


## 2.2 Array Attributes

NumPy arrays come with various attributes that give information about their structure and data:

1. **`ndim`**: The number of dimensions (or axes) of the array.


In [ ]:
print("Number of dimensions (ndim):", arr_2d.ndim)

Number of dimensions (ndim): 2


2. **`shape`**: The shape of the array (a tuple representing the size along each dimension).



In [ ]:
print("Shape of the array:", arr_2d.shape)

Shape of the array: (2, 3)


3. **`size`**: The total number of elements in the array.

In [ ]:
print("Total number of elements (size):", arr_2d.size)

Total number of elements (size): 6


4. **`dtype`**: The data type of the elements in the array.

In [ ]:
print("Data type of the array:", arr_2d.dtype)

Data type of the array: int32


5. **`itemsize`**: The size (in bytes) of each element in the array.

In [ ]:
print("Size of each element (itemsize):", arr_2d.itemsize, "bytes")

Size of each element (itemsize): 4 bytes


### Reshaping Arrays

NumPy allows you to change the shape of an array without modifying its data. This is useful when you want to organize your data in a different format.

1. **`reshape()`**: You can change the shape of an array to any compatible shape (i.e., the new shape must have the same total number of elements as the original array).



In [ ]:
arr = np.arange(6)  # Creates a 1D array [0, 1, 2, 3, 4, 5]
reshaped_arr = arr.reshape((2, 3))  # Reshapes it to a 2D array (2x3)
print("Original array:", arr)
print("Reshaped array:\n", reshaped_arr)

Original array: [0 1 2 3 4 5]
Reshaped array:
 [[0 1 2]
 [3 4 5]]


2. **`ravel()`**: Flattens the array into a 1D array.

In [ ]:
flattened_arr = reshaped_arr.ravel()
print("Flattened array:", flattened_arr)


Flattened array: [0 1 2 3 4 5]


****
# 3.1 Indexing in NumPy

Indexing allows you to access individual elements or groups of elements from NumPy arrays. Let's explore how to index 1D, 2D, and multi-dimensional arrays.

### 1D Arrays

For a 1D array, you can access elements using their index, which starts at 0.


In [ ]:
import numpy as np

# Creating a 1D NumPy array
arr_1d = np.array([10, 20, 30, 40, 50])

# Accessing individual elements
print("First element:", arr_1d[0])  # Output: 10
print("Third element:", arr_1d[2])  # Output: 30

First element: 10
Third element: 30


### 2D Arrays

In 2D arrays, you need to specify both the row and column indices.


In [ ]:
# Creating a 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing individual elements
print("Element at row 1, column 2:", arr_2d[1, 2])  # Output: 6
print("Element at row 0, column 0:", arr_2d[0, 0])  # Output: 1

Element at row 1, column 2: 6
Element at row 0, column 0: 1


### Multi-Dimensional Arrays

For multi-dimensional arrays, the indexing approach remains similar, with additional indices as required by the number of dimensions.

In [ ]:
# Creating a 3D NumPy array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Accessing individual elements
print("Element at [1, 0, 1]:", arr_3d[1, 0, 1])  # Output: 6
print("Element at [0, 1, 0]:", arr_3d[0, 1, 0])  # Output: 3


Element at [1, 0, 1]: 6
Element at [0, 1, 0]: 3


## 3.2 Slicing NumPy Arrays

Slicing allows you to extract a portion of an array by specifying a range of indices. The general syntax for slicing is `array[start:stop:step`, where `start` is the starting index (inclusive), `stop` is the stopping index (exclusive), and `step` defines the stride.

### Slicing Arrays Using Colon `:`

For a 1D array, you can slice using the colon operator.


In [ ]:
# Slicing a 1D array
slice_1d = arr_1d[1:4]  # Elements from index 1 to 3
print("Slice of 1D array:", slice_1d)  # Output: [20 30 40]


Slice of 1D array: [20 30 40]


### Slicing 2D Arrays

For 2D arrays, you can slice rows and columns independently.


In [ ]:
# Slicing a 2D array
slice_2d = arr_2d[0:2, 1:3]  # Rows 0 to 1 and columns 1 to 2
print("Slice of 2D array:\n", slice_2d)

Slice of 2D array:
 [[2 3]
 [5 6]]


### Using Steps and Reverse Slicing

You can also specify a step size in your slicing to skip elements.


In [ ]:
# Using steps in slicing
step_slice = arr_1d[::2]  # Every second element
print("Every second element in 1D array:", step_slice)  # Output: [10 30 50]

# Reverse slicing
reverse_slice = arr_1d[::-1]  # Reversing the array
print("Reversed 1D array:", reverse_slice)  # Output: [50 40 30 20 10]

Every second element in 1D array: [10 30 50]
Reversed 1D array: [50 40 30 20 10]


### Slicing in Multi-Dimensional Arrays

You can slice multi-dimensional arrays similarly, specifying ranges for each dimension.

In [ ]:
# Slicing a 3D array
slice_3d = arr_3d[1, :, 0]  # Selecting all elements from the second 'plane', first column
print("Slice of 3D array:\n", slice_3d)


Slice of 3D array:
 [5 7]


## 3.3 Advanced Indexing

In addition to basic indexing and slicing, NumPy provides advanced indexing techniques that allow for more sophisticated ways to access and manipulate data in arrays. This section covers Boolean indexing and fancy indexing.

### Boolean Indexing

Boolean indexing is a powerful feature that allows you to select elements from an array based on conditions. You create a boolean array that has the same shape as the original array, where each element is `True` or `False`, depending on whether the condition is met.

#### Using Boolean Conditions

Here's how to use boolean indexing to filter elements in a NumPy array:


In [ ]:
import numpy as np

# Creating a NumPy array
arr = np.array([10, 20, 30, 40, 50, 60])

# Creating a boolean condition to filter elements greater than 30
condition = arr > 30
print("Boolean condition (arr > 30):", condition)  # Output: [False False False  True  True  True]

# Using the boolean condition to get elements
filtered_elements = arr[condition]
print("Filtered elements (greater than 30):", filtered_elements)  # Output: [40 50 60]


Boolean condition (arr > 30): [False False False  True  True  True]
Filtered elements (greater than 30): [40 50 60]


### Combining Conditions

You can combine multiple boolean conditions using logical operators (`&` for AND, `|` for OR):


In [ ]:
# Filtering elements greater than 20 and less than 50
filtered_combined = arr[(arr > 20) & (arr < 50)]
print("Filtered elements (greater than 20 and less than 50):", filtered_combined)  # Output: [30 40]


Filtered elements (greater than 20 and less than 50): [30 40]


### Fancy Indexing

Fancy indexing allows you to access multiple array elements at once using arrays of indices. This technique can be particularly useful when you want to select specific rows or columns from a 2D array.

#### Using Arrays of Indices

Here's how to use fancy indexing with NumPy:


In [ ]:
# Creating a 2D NumPy array
arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Fancy indexing with a list of row indices and column indices
rows = np.array([0, 1, 2])  # Row indices
cols = np.array([1, 2, 0])  # Column indices

fancy_indexed_elements = arr_2d[rows, cols]
print("Fancy indexed elements:", fancy_indexed_elements)  # Output: [20 60 70]


Fancy indexed elements: [20 60 70]


### Selecting Rows and Columns

Fancy indexing can also be used to select entire rows or columns from an array:


In [ ]:
# Selecting specific rows
selected_rows = arr_2d[[0, 2], :]  # Select rows 0 and 2
print("Selected rows:\n", selected_rows)

# Selecting specific columns
selected_columns = arr_2d[:, [0, 2]]  # Select columns 0 and 2
print("Selected columns:\n", selected_columns)


Selected rows:
 [[10 20 30]
 [70 80 90]]
Selected columns:
 [[10 30]
 [40 60]
 [70 90]]


****
# 4. Array Operations

NumPy provides a variety of array operations that enable efficient computation and data manipulation. This section covers basic arithmetic operations, mathematical functions, and linear algebra operations.

## 4.1 Basic Arithmetic Operations

NumPy allows you to perform arithmetic operations on arrays element-wise. This means that when you perform operations on two arrays, NumPy applies the operation to corresponding elements.

### Element-wise Operations

Here are examples of element-wise addition, subtraction, multiplication, and division:


In [ ]:
import numpy as np

# Creating two NumPy arrays
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

# Element-wise addition
addition_result = arr1 + arr2
print("Element-wise addition:", addition_result)  # Output: [11 22 33]

# Element-wise subtraction
subtraction_result = arr1 - arr2
print("Element-wise subtraction:", subtraction_result)  # Output: [ 9 18 27]

# Element-wise multiplication
multiplication_result = arr1 * arr2
print("Element-wise multiplication:", multiplication_result)  # Output: [10 40 90]

# Element-wise division
division_result = arr1 / arr2
print("Element-wise division:", division_result)  # Output: [10. 10. 10.]


Element-wise addition: [11 22 33]
Element-wise subtraction: [ 9 18 27]
Element-wise multiplication: [10 40 90]
Element-wise division: [10. 10. 10.]


### Broadcasting Concept in NumPy

Broadcasting is a powerful feature in NumPy that allows you to perform arithmetic operations on arrays of different shapes. NumPy automatically expands the smaller array across the larger array to match their shapes.


In [ ]:
# Creating a 1D array and a 2D array
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[10, 20, 30], [40, 50, 60]])

# Broadcasting: adding a 1D array to a 2D array
broadcast_result = arr_2d + arr_1d
print("Result of broadcasting:\n", broadcast_result)


Result of broadcasting:
 [[11 22 33]
 [41 52 63]]


## 4.2 Mathematical Functions

NumPy provides built-in mathematical functions that allow you to perform operations efficiently.

### Using Built-in NumPy Functions

You can use functions like `np.add()`, `np.subtract()`, `np.multiply()`, and `np.divide()` to perform arithmetic operations.


In [ ]:
# Using built-in functions
add_result = np.add(arr1, arr2)
print("Addition using np.add():", add_result)  # Output: [11 22 33]

subtract_result = np.subtract(arr1, arr2)
print("Subtraction using np.subtract():", subtract_result)  # Output: [ 9 18 27]

multiply_result = np.multiply(arr1, arr2)
print("Multiplication using np.multiply():", multiply_result)  # Output: [10 40 90]

divide_result = np.divide(arr1, arr2)
print("Division using np.divide():", divide_result)  # Output: [10. 10. 10.]


Addition using np.add(): [11 22 33]
Subtraction using np.subtract(): [ 9 18 27]
Multiplication using np.multiply(): [10 40 90]
Division using np.divide(): [10. 10. 10.]


### Aggregation Functions

NumPy also offers aggregation functions that help you summarize data:


In [ ]:
# Aggregation functions
sum_result = np.sum(arr1)
print("Sum of elements:", sum_result)  # Output: 60

prod_result = np.prod(arr1)
print("Product of elements:", prod_result)  # Output: 6000

mean_result = np.mean(arr1)
print("Mean of elements:", mean_result)  # Output: 20.0

std_result = np.std(arr1)
print("Standard deviation:", std_result)  # Output: 10.0

var_result = np.var(arr1)
print("Variance:", var_result)  # Output: 100.0


Sum of elements: 60
Product of elements: 6000
Mean of elements: 20.0
Standard deviation: 8.16496580927726
Variance: 66.66666666666667


## 4.3 Linear Algebra Operations

NumPy provides functionality for performing various linear algebra operations.

### Matrix Multiplication: `np.dot()`

You can perform matrix multiplication using the `np.dot()` function.


In [ ]:
# Creating two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
dot_result = np.dot(matrix1, matrix2)
print("Matrix multiplication result:\n", dot_result)


Matrix multiplication result:
 [[19 22]
 [43 50]]


### Determinants, Eigenvalues, and Inverse

You can compute the determinant, eigenvalues, and inverse of a matrix using functions from the `np.linalg` module.


In [ ]:
# Determinant
det_result = np.linalg.det(matrix1)
print("Determinant:", det_result)  # Output: -2.0

# Inverse
inv_result = np.linalg.inv(matrix1)
print("Inverse of the matrix:\n", inv_result)


Determinant: -2.0000000000000004
Inverse of the matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


### Solving Linear Equations: `np.linalg.solve()`

To solve a system of linear equations, you can use the `np.linalg.solve()` function.


In [ ]:
# Coefficient matrix
A = np.array([[3, 1], [1, 2]])
# Right-hand side
b = np.array([9, 8])

# Solving the system of equations
solution = np.linalg.solve(A, b)
print("Solution to the linear equations:", solution)  # Output: [ 2.  3.]


Solution to the linear equations: [2. 3.]


# 5. NumPy Array Manipulation

NumPy offers various functions to manipulate arrays, including joining, splitting, transposing, and swapping axes. This section covers joining and splitting arrays and transposing and swapping axes.

## 5.1 Joining and Splitting Arrays

Joining and splitting arrays are fundamental operations that allow you to combine multiple arrays into one or break a single array into multiple parts.

### Concatenating Arrays

You can concatenate arrays using functions like `np.concatenate()`, `np.vstack()`, and `np.hstack()`.

#### Using `np.concatenate()`

This function joins a sequence of arrays along a specified axis:


In [ ]:
import numpy as np

# Creating two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenating 1D arrays
concat_result_1d = np.concatenate((arr1, arr2))
print("Concatenated 1D array:", concat_result_1d)  # Output: [1 2 3 4 5 6]

# Creating two 2D arrays
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6]])

# Concatenating 2D arrays along axis 0 (rows)
concat_result_2d_axis0 = np.concatenate((arr3, arr4), axis=0)
print("Concatenated 2D array (axis 0):\n", concat_result_2d_axis0)

# Concatenating 2D arrays along axis 1 (columns)
concat_result_2d_axis1 = np.concatenate((arr3, arr4.T), axis=1)  # Transposing arr4 to match dimensions
print("Concatenated 2D array (axis 1):\n", concat_result_2d_axis1)


Concatenated 1D array: [1 2 3 4 5 6]
Concatenated 2D array (axis 0):
 [[1 2]
 [3 4]
 [5 6]]
Concatenated 2D array (axis 1):
 [[1 2 5]
 [3 4 6]]


### Using `np.vstack()` and `np.hstack()`

These functions are shortcuts for vertical and horizontal stacking:


In [ ]:
# Vertical stacking (rows)
vstack_result = np.vstack((arr3, arr4))
print("Vertical stack result:\n", vstack_result)

# Horizontal stacking (columns)
hstack_result = np.hstack((arr3, arr4.T))  # Transposing arr4 to match dimensions
print("Horizontal stack result:\n", hstack_result)


Vertical stack result:
 [[1 2]
 [3 4]
 [5 6]]
Horizontal stack result:
 [[1 2 5]
 [3 4 6]]


### Splitting Arrays

You can split arrays into multiple sub-arrays using functions like `np.split()`, `np.vsplit()`, and `np.hsplit()`.

#### Using `np.split()`

This function splits an array into multiple sub-arrays along a specified axis:


In [ ]:
# Creating a 1D array
arr5 = np.array([1, 2, 3, 4, 5, 6])

# Splitting the array into 3 equal parts
split_result = np.split(arr5, 3)
print("Split result:", split_result)  # Output: [array([1, 2]), array([3, 4]), array([5, 6])]

# Creating a 2D array with 6 rows
arr6 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

# Splitting the 2D array vertically into 3 equal parts
vsplit_result = np.vsplit(arr6, 3)
print("Vertical split result:\n", vsplit_result)

Split result: [array([1, 2]), array([3, 4]), array([5, 6])]
Vertical split result:
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


#### Using `np.hsplit()`

This function splits an array horizontally:


In [ ]:
# Splitting the 2D array horizontally (into 2 arrays)
hsplit_result = np.hsplit(arr6, 2)
print("Horizontal split result:", hsplit_result)  # Output: [array([[1], [3], [5]]), array([[2], [4], [6]])]

Horizontal split result: [array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])]


## 5.2 Transposing and Swapping Axes

Transposing and swapping axes are essential operations for manipulating the orientation of arrays.

### Transposing Arrays: `np.transpose()`

The `np.transpose()` function permutes the dimensions of an array, effectively flipping it over its diagonal.


In [ ]:
# Creating a 2D array
arr7 = np.array([[1, 2, 3], [4, 5, 6]])

# Transposing the array
transposed_result = np.transpose(arr7)
print("Transposed array:\n", transposed_result)


Transposed array:
 [[1 4]
 [2 5]
 [3 6]]


### Changing Array Axes with `np.swapaxes()`

The `np.swapaxes()` function allows you to swap two specified axes of an array.


In [ ]:
# Swapping axes of a 2D array
swapped_result = np.swapaxes(arr7, 0, 1)  # Swapping axis 0 (rows) with axis 1 (columns)
print("Array after swapping axes:\n", swapped_result)


Array after swapping axes:
 [[1 4]
 [2 5]
 [3 6]]


****
# 6. Broadcasting in NumPy

## 6.1 Introduction to Broadcasting

### What is Broadcasting?

Broadcasting in NumPy is a powerful mechanism that allows arithmetic operations to be performed on arrays of different shapes and sizes. When performing operations on arrays, NumPy automatically expands the smaller array to match the shape of the larger array. This allows for efficient and intuitive operations without the need for explicit replication of data.

### Rules of Broadcasting

There are specific rules that govern how NumPy handles broadcasting:

1. **Dimensions Compatibility**: If the arrays do not have the same number of dimensions, NumPy pads the shape of the smaller array with ones on the left side until both shapes are the same.

2. **Size Compatibility**: Two dimensions are compatible when:
   - They are equal, or
   - One of them is 1.

3. **Array Expansion**: If the dimensions of the arrays do not match, NumPy will stretch the smaller array across the larger array until they are compatible.

### Example of Broadcasting Rules

Let’s explore how these rules work with some examples.


In [ ]:
import numpy as np

# Create a 2D array (3x3)
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Create a 1D array (1x3)
array_1d = np.array([10, 20, 30])

# Broadcasting: Adding a 1D array to a 2D array
result = array_2d + array_1d
print("Result of broadcasting:\n", result)

Result of broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


- In this example, the 1D array is broadcasted to match the shape of the 2D array. The smaller array is added to each row of the larger array.



## 6.2 Broadcasting Examples

Now, let’s look at some practical examples of broadcasting in array operations.

### Example 1: Adding a Scalar to an Array

When you add a scalar (single value) to an array, the scalar is broadcasted to all elements of the array.


In [ ]:
# Creating a 1D array
array = np.array([1, 2, 3, 4, 5])

# Adding a scalar value
scalar_result = array + 5
print("Result of adding scalar:\n", scalar_result)


Result of adding scalar:
 [ 6  7  8  9 10]


### Example 2: Subtracting a 1D Array from a 2D Array

Here’s how a 1D array can be subtracted from a 2D array, demonstrating broadcasting.


In [ ]:
# Creating a 2D array
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])

# Subtracting a 1D array
array_1d = np.array([1, 2, 3])
result_subtract = array_2d - array_1d
print("Result of subtracting a 1D array:\n", result_subtract)

Result of subtracting a 1D array:
 [[ 9 18 27]
 [39 48 57]
 [69 78 87]]


### Example 3: Multiplying Arrays of Different Shapes

You can also multiply arrays of different shapes, as long as they are compatible according to the broadcasting rules.


In [ ]:
# Creating a 3D array
array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6]],

                     [[7, 8, 9],
                      [10, 11, 12]]])

# Creating a 1D array
array_1d = np.array([2, 3, 4])

# Broadcasting for multiplication
result_multiply = array_3d * array_1d
print("Result of multiplying with a 1D array:\n", result_multiply)


Result of multiplying with a 1D array:
 [[[ 2  6 12]
  [ 8 15 24]]

 [[14 24 36]
  [20 33 48]]]


****
# 7. Working with Random Numbers

## 7.1 Random Number Generation

### Generating Random Numbers

NumPy provides a range of functions for generating random numbers. The most commonly used functions include:

- `np.random.rand()`: Generates random numbers in a uniform distribution over the interval \([0.0, 1.0)\).
- `np.random.randint()`: Generates random integers within a specified range.

### Example: Generating Random Numbers


In [ ]:
import numpy as np

# Generating 5 random numbers between 0 and 1
random_floats = np.random.rand(5)
print("Random floats between 0 and 1:", random_floats)

# Generating 5 random integers between 0 and 10
random_integers = np.random.randint(0, 10, size=5)
print("Random integers between 0 and 10:", random_integers)

Random floats between 0 and 1: [0.34512642 0.92052229 0.52250164 0.15854366 0.59219072]
Random integers between 0 and 10: [8 1 2 1 6]


### Random Sampling and Shuffling

NumPy also allows for random sampling and shuffling of arrays.

- `np.random.shuffle()`: Shuffles the array in place.

##### Example: Random Sampling and Shuffling


In [ ]:
# Creating an array
arr = np.array([1, 2, 3, 4, 5, 6])

# Shuffling the array
np.random.shuffle(arr)
print("Shuffled array:", arr)


Shuffled array: [4 1 2 5 6 3]


## 7.2 Statistical Distributions

NumPy provides functions to work with various statistical distributions, such as normal, uniform, and binomial distributions.

### Normal Distribution

The normal distribution is a continuous probability distribution defined by a mean and standard deviation.

- `np.random.normal(loc, scale, size)`: Generates random samples from a normal distribution with a given mean (`loc`) and standard deviation (`scale`).

##### Example: Normal Distribution


In [ ]:
# Generating 1000 random numbers from a normal distribution
mean = 0
std_dev = 1
normal_samples = np.random.normal(mean, std_dev, size=1000)

# Displaying the first 10 samples
print("First 10 samples from normal distribution:", normal_samples[:10])


First 10 samples from normal distribution: [ 0.81308682  0.06739897  1.02873129 -0.47508258  0.19541584 -0.7608256
  0.64213724  0.15322831  0.92806136  1.52277928]


### Uniform Distribution

The uniform distribution is a type of distribution where all outcomes are equally likely.

- `np.random.uniform(low, high, size)`: Generates random samples from a uniform distribution over the half-open interval \([low, high)\).

##### Example: Uniform Distribution


In [ ]:
# Generating 5 random numbers from a uniform distribution
uniform_samples = np.random.uniform(1, 10, size=5)
print("Random samples from uniform distribution:", uniform_samples)


Random samples from uniform distribution: [4.48967163 9.35192288 8.80380683 6.14654207 1.31133835]


### Binomial Distribution

The binomial distribution represents the number of successes in a fixed number of independent Bernoulli trials.

- `np.random.binomial(n, p, size)`: Generates random samples from a binomial distribution with \( n \) trials and probability of success \( p \).

##### Example: Binomial Distribution


In [ ]:
# Generating 10 random samples from a binomial distribution
n_trials = 10  # Number of trials
p_success = 0.5  # Probability of success
binomial_samples = np.random.binomial(n_trials, p_success, size=10)
print("Random samples from binomial distribution:", binomial_samples)


Random samples from binomial distribution: [2 4 3 4 4 7 8 7 8 2]


****
# 8. NumPy for Data Analysis

## 8.1 Statistical Functions

NumPy provides various statistical functions that are essential for data analysis. These functions allow you to perform calculations like finding the minimum, maximum, and percentiles, as well as cumulative sums and products.

#### Calculating Minimum, Maximum, and Percentiles

- `np.min()`: Returns the minimum value in an array.
- `np.max()`: Returns the maximum value in an array.
- `np.percentile()`: Computes the nth percentile of the data along a specified axis.

##### Example: Minimum, Maximum, and Percentiles


In [ ]:
import numpy as np

# Creating a sample array
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Calculating minimum and maximum
minimum = np.min(data)
maximum = np.max(data)

# Calculating percentiles
percentile_25 = np.percentile(data, 25)
percentile_50 = np.percentile(data, 50)  # This is the median
percentile_75 = np.percentile(data, 75)

print(f"Minimum: {minimum}, Maximum: {maximum}")
print(f"25th Percentile: {percentile_25}, 50th Percentile: {percentile_50}, 75th Percentile: {percentile_75}")


Minimum: 10, Maximum: 90
25th Percentile: 30.0, 50th Percentile: 50.0, 75th Percentile: 70.0


### Cumulative Sum and Product

- `np.cumsum()`: Returns the cumulative sum of the elements along a given axis.
- `np.cumprod()`: Returns the cumulative product of the elements along a given axis.

##### Example: Cumulative Sum and Product


In [ ]:
# Creating a sample array
data = np.array([1, 2, 3, 4, 5])

# Calculating cumulative sum and product
cumulative_sum = np.cumsum(data)
cumulative_product = np.cumprod(data)

print(f"Cumulative Sum: {cumulative_sum}")
print(f"Cumulative Product: {cumulative_product}")


Cumulative Sum: [ 1  3  6 10 15]
Cumulative Product: [  1   2   6  24 120]


## 8.2 Sorting and Searching in Arrays

NumPy offers functions for sorting and searching elements within arrays, making it easier to analyze data.

### Sorting Arrays

- `np.sort()`: Returns a sorted copy of an array. The original array remains unchanged. You can specify the axis to sort along.

##### Example: Sorting Arrays


In [ ]:
# Creating a sample array
data = np.array([5, 2, 9, 1, 5, 6])

# Sorting the array
sorted_data = np.sort(data)
print("Original array:", data)
print("Sorted array:", sorted_data)


Original array: [5 2 9 1 5 6]
Sorted array: [1 2 5 5 6 9]


### Searching Elements in Arrays

- `np.where()`: Returns the indices of elements in an array that satisfy a given condition.
- `np.searchsorted()`: Finds indices where elements should be inserted to maintain order.

##### Example: Searching Elements


In [ ]:
# Creating a sample array
data = np.array([1, 3, 5, 7, 9])

# Finding indices of elements that are greater than 5
indices = np.where(data > 5)
print("Indices of elements greater than 5:", indices)

# Using searchsorted to find index to insert new values
insert_value = 6
insert_index = np.searchsorted(data, insert_value)
print(f"Index to insert {insert_value} to maintain order: {insert_index}")


Indices of elements greater than 5: (array([3, 4], dtype=int64),)
Index to insert 6 to maintain order: 3


****
## 9. NumPy and Memory Efficiency

Understanding memory efficiency in NumPy is crucial for optimizing performance, especially when working with large datasets. This section covers the memory layout of arrays and how to perform memory-efficient operations.

### 9.1 Memory Layout

NumPy arrays can be stored in different memory layouts, which can affect performance. The two primary layouts are C-order (row-major) and F-order (column-major).

#### C-order vs. F-order

- **C-order**: In C-order (or row-major order), elements are stored row by row. This means that consecutive elements of a row are stored in adjacent memory locations. This layout is the default for NumPy arrays.

- **F-order**: In F-order (or column-major order), elements are stored column by column. This means that consecutive elements of a column are stored in adjacent memory locations.

##### Example: Array Memory Layout

You can check the memory layout of an array using the `order` parameter when creating the array and using the `ndarray.flags` attribute to check the memory layout.

In [ ]:
import numpy as np

# Creating a 2D array in C-order
array_c = np.array([[1, 2, 3], [4, 5, 6]], order='C')
print("C-order array:")
print(array_c)
print("C-order layout:", array_c.flags['C_CONTIGUOUS'])

# Creating a 2D array in F-order
array_f = np.array([[1, 2, 3], [4, 5, 6]], order='F')
print("\nF-order array:")
print(array_f)
print("F-order layout:", array_f.flags['F_CONTIGUOUS'])


C-order array:
[[1 2 3]
 [4 5 6]]
C-order layout: True

F-order array:
[[1 2 3]
 [4 5 6]]
F-order layout: True


### 9.2 Memory Efficient Operations

When working with NumPy arrays, performing operations efficiently can help save memory and improve performance.

#### In-place Operations

In-place operations modify the array without creating a copy. This can significantly save memory, especially with large datasets. You can use operations like `+=`, `-=`, `*=`, and `/=` for in-place modifications.

##### Example: In-place Operations


In [ ]:
# Creating a sample array
data = np.array([1, 2, 3, 4, 5])

# Performing in-place addition
data += 10
print("Array after in-place addition:", data)


Array after in-place addition: [11 12 13 14 15]


### Copying vs. Viewing Arrays

##### Copying
- When you use the `copy()` method, a new array is created, and changes to the new array do not affect the original array.

##### Viewing
- When you use the `view()` method, a new view of the original array is created. Changes to the view will affect the original array because both share the same data buffer.

##### Example: Copying vs. Viewing

In [ ]:
# Creating a sample array
original = np.array([1, 2, 3, 4, 5])

# Creating a copy
copied_array = original.copy()
copied_array[0] = 10  # Modify the copied array
print("Original array after modifying copied array:", original)

# Creating a view
viewed_array = original.view()
viewed_array[0] = 20  # Modify the viewed array
print("Original array after modifying viewed array:", original)


Original array after modifying copied array: [1 2 3 4 5]
Original array after modifying viewed array: [20  2  3  4  5]


****
## 10. NumPy for Advanced Users

In this section, we will explore advanced features of NumPy that can help you handle complex data structures and manage missing data efficiently. We'll cover structured arrays and masked arrays, providing examples and explanations for each.

### 10.1 Structured Arrays
Structured arrays allow you to create arrays with different data types for each column, similar to a table in a database or a DataFrame in pandas. This is useful when you want to group related data together.

#### Creating and Manipulating Structured Arrays
You can create structured arrays by defining a data type using `np.dtype()` and then passing a list of tuples or dictionaries to create the array.

##### Example: Creating a Structured Array


In [ ]:
import numpy as np

# Define a structured data type
dtype = np.dtype([('name', 'U10'), ('age', 'i4'), ('height', 'f4')])

# Create a structured array
data = np.array([('Alice', 25, 5.5), ('Bob', 30, 6.0)], dtype=dtype)

print("Structured Array:")
print(data)


Structured Array:
[('Alice', 25, 5.5) ('Bob', 30, 6. )]


#### Accessing Structured Array Fields
You can access the fields of a structured array using the field names. This allows for easy manipulation and retrieval of specific data.

##### Example: Accessing Fields


In [ ]:
# Accessing the 'name' field
names = data['name']
print("Names:", names)

# Accessing the 'age' field
ages = data['age']
print("Ages:", ages)

# Accessing the 'height' field
heights = data['height']
print("Heights:", heights)

Names: ['Alice' 'Bob']
Ages: [25 30]
Heights: [5.5 6. ]


### 10.2 Masked Arrays
Masked arrays are used to handle missing or invalid data. With masked arrays, you can mask certain elements of an array, effectively ignoring them in calculations and analyses.

#### Working with Missing Data Using Masked Arrays
You can create a masked array using `np.ma.array()`, where you specify the mask to indicate which values are valid or invalid.

##### Example: Creating a Masked Array


In [ ]:
# Creating a regular array
data = np.array([1, 2, np.nan, 4, 5])

# Creating a masked array
masked_data = np.ma.masked_array(data, mask=np.isnan(data))

print("Masked Array:")
print(masked_data)


Masked Array:
[1.0 2.0 -- 4.0 5.0]


##### Example: Performing Calculations with Masked Arrays
Operations on masked arrays automatically ignore the masked elements. This allows you to perform calculations without having to manually filter out invalid data.


In [ ]:
# Calculate the mean while ignoring the masked values
mean_value = np.ma.mean(masked_data)
print("Mean (ignoring masked values):", mean_value)


Mean (ignoring masked values): 3.0


****
### 11. File Input/Output with NumPy

File input and output (I/O) is essential for data analysis, as it allows you to save and load arrays for later use. NumPy provides various functions to handle file I/O efficiently. In this section, we will cover saving and loading arrays, working with .npy and .npz files, and how to save multiple arrays in one file.

#### 11.1 Saving and Loading Arrays
NumPy provides functions to save and load arrays in both text and binary formats.

**Saving Arrays to Text and Binary Files**
- **np.savetxt()**: This function is used to save arrays to a text file. You can specify the delimiter and format for the output.
- **np.save()**: This function saves an array to a binary file with a .npy extension.

##### Example: Saving Arrays
```python
import numpy as np

# Create a NumPy array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Save the array to a text file
np.savetxt('array.txt', array, delimiter=',', fmt='%d')

# Save the array to a binary file
np.save('array.npy', array)


In [ ]:
import numpy as np

# Create an array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Save the array to a text file
np.savetxt('array.txt', array, delimiter=',', fmt='%d')
print("Array saved to array.txt")

# Save the array to a binary file
np.save('array.npy', array)
print("Array saved to array.npy")

Array saved to array.txt
Array saved to array.npy


#### Loading Arrays from Files
- **np.loadtxt()**: This function is used to load arrays from a text file.
- **np.load()**: This function loads arrays from a binary file.

##### Example: Loading Arrays
```python
import numpy as np

# Load the array from a text file
loaded_array_txt = np.loadtxt('array.txt', delimiter=',')
print("Loaded array from text file:")
print(loaded_array_txt)

# Load the array from a binary file
loaded_array_bin = np.load('array.npy')
print("Loaded array from binary file:")
print(loaded_array_bin)


In [ ]:
# Load the array from the text file
loaded_array_txt = np.loadtxt('array.txt', delimiter=',')
print("Loaded array from text file:")
print(loaded_array_txt)

# Load the array from the binary file
loaded_array_bin = np.load('array.npy')
print("\nLoaded array from binary file:")
print(loaded_array_bin)

Loaded array from text file:
[[1. 2. 3.]
 [4. 5. 6.]]

Loaded array from binary file:
[[1 2 3]
 [4 5 6]]


#### Working with .npy and .npz Files
- **Saving Multiple Arrays in One File**: The `.npy` format is ideal for saving single arrays, while the `.npz` format allows you to save multiple arrays in a single file. You can use the **np.savez()** function for this purpose.

##### Example: Saving Multiple Arrays
```python
import numpy as np

# Create some example arrays
array1 = np.array([1, 2, 3])
array2 = np.array([[4, 5], [6, 7]])
array3 = np.array([[8, 9, 10]])

# Save multiple arrays in a single .npz file
np.savez('multiple_arrays.npz', array1=array1, array2=array2, array3=array3)

print("Arrays saved in 'multiple_arrays.npz'")


In [ ]:
# Create multiple arrays
array1 = np.array([1, 2, 3])
array2 = np.array([[4, 5, 6], [7, 8, 9]])

# Save multiple arrays into a single .npz file
np.savez('multiple_arrays.npz', array1=array1, array2=array2)
print("Multiple arrays saved to multiple_arrays.npz")


Multiple arrays saved to multiple_arrays.npz


#### Loading Multiple Arrays
You can load the arrays from a `.npz` file using **np.load()**, which returns a dictionary-like object that allows you to access each array by its name.

##### Example: Loading Multiple Arrays
```python
import numpy as np

# Load the arrays from the .npz file
data = np.load('multiple_arrays.npz')

# Accessing the individual arrays
array1 = data['array1']
array2 = data['array2']
array3 = data['array3']

print("Loaded array1:", array1)
print("Loaded array2:", array2)
print("Loaded array3:", array3)


In [ ]:
# Load the arrays from the .npz file
loaded_arrays = np.load('multiple_arrays.npz')

# Access the arrays
loaded_array1 = loaded_arrays['array1']
loaded_array2 = loaded_arrays['array2']

print("\nLoaded array1:")
print(loaded_array1)

print("\nLoaded array2:")
print(loaded_array2)


Loaded array1:
[1 2 3]

Loaded array2:
[[4 5 6]
 [7 8 9]]


****
### 12. Best Practices and Optimization
To effectively use NumPy for data analysis and scientific computing, it’s essential to follow best practices and optimization techniques. This section covers the best practices for using NumPy efficiently and tips for improving performance.

#### 12.1 Best Practices in NumPy

**Choosing Data Types for Performance**
Selecting appropriate data types can significantly impact memory usage and performance. NumPy supports various data types, including integers, floats, and booleans. Choosing the right data type can reduce memory consumption and improve computation speed.

##### Example of Specifying Data Types:
```python
import numpy as np

# Creating an array with a specified data type
array_int = np.array([1, 2, 3, 4], dtype=np.int8)  # Using int8 for smaller memory usage
array_float = np.array([1.0, 2.0, 3.0, 4.0], dtype=np.float32)  # Using float32 for reduced memory

print("Array with int8 data type:", array_int)
print("Array with float32 data type:", array_float)


In [ ]:
import numpy as np

# Creating arrays with specific data types
int_array = np.array([1, 2, 3], dtype='int32')  # 32-bit integer
float_array = np.array([1.0, 2.0, 3.0], dtype='float64')  # 64-bit float

**Avoiding Unnecessary Array Copying**

Array copying can lead to increased memory usage and slower performance. When you create a new array from an existing one, be mindful of whether you need a copy or can use a view.

##### Using Views Instead of Copies:

In [ ]:
original_array = np.array([1, 2, 3, 4, 5])

# Creating a view of the original array
view_array = original_array[2:4]  # This creates a view, not a copy
view_array[0] = 99  # This modifies the original array

print("Original array after modifying the view:")
print(original_array)  # Output: [ 1  2 99  4  5]


Original array after modifying the view:
[ 1  2 99  4  5]


**12.2 Performance Optimization**

**Vectorization and Avoiding Loops**

Vectorization is a core feature of NumPy that allows you to perform operations on entire arrays without writing explicit loops. By utilizing NumPy's built-in functions, you can avoid slower Python loops and take advantage of highly optimized C and Fortran libraries, leading to faster execution and more concise code.


In [ ]:
import numpy as np

# Create two large arrays
array1 = np.random.rand(1000000)
array2 = np.random.rand(1000000)

# Element-wise addition using vectorization
result = array1 + array2  # This is faster than using a loop
result

array([1.28282759, 0.3775158 , 0.61731513, ..., 0.81824287, 1.63160978,
       1.75649915])

**Using `numexpr` and Cython for Performance Improvements**

**`numexpr`:** This library allows you to evaluate array expressions more efficiently than using NumPy alone by utilizing multiple CPU cores and optimizing memory usage. It can lead to significant performance improvements, especially for large datasets and complex expressions.


In [ ]:
import numexpr as ne

# Evaluate the expression using numexpr
result = ne.evaluate("array1 + array2")
result

array([1.28282759, 0.3775158 , 0.61731513, ..., 0.81824287, 1.63160978,
       1.75649915])

**Cython:**
Cython is a tool that allows you to write C extensions for Python. It compiles Python code into C, leading to significant performance improvements, especially for numerical computations and loops. By converting Python code into C code, Cython can make your code run much faster, which is particularly useful for heavy computational tasks.

##### Example of Using Cython:
Here’s an example that demonstrates the use of Cython to optimize a Python function.

1. **First, you need to create a Cython file** (with the `.pyx` extension) that contains the optimized code.

**`cython_example.pyx`:**
```python
def sum_of_squares(int n):
    cdef int i
    cdef double total = 0
    for i in range(n):
        total += i * i
    return total


In [ ]:
!pip install cython

In [ ]:
import numpy as np
cimport numpy as np

# Define a Cython function
def cython_add(np.ndarray[float, ndim=1] arr1, np.ndarray[float, ndim=1] arr2):
    cdef int i
    cdef int n = arr1.shape[0]
    cdef np.ndarray[float, ndim=1] result = np.empty(n, dtype=np.float64)

    for i in range(n):
        result[i] = arr1[i] + arr2[i]
    return result


## Happy Learning!